#ifndef QTCOMLIBRARY_GLOBAL_H
#define QTCOMLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTCOMLIBRARY_LIBRARY)
#  define QTCOMLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTCOMLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTCOMLIBRARY_GLOBAL_H
